### ISSUE TITLE
Bot stalling in trade

### ISSUE THREAD

**Issue by Wolfling1** [kwsch/SysBot.NET#103]
Before i'm told to read the wiki, i've read it like 5 times in the past day and i haven't seen anything about this,

After trading, my bot won't leave the trade immediately. This happens in both discord trades and idle distribution trades.
It will select the pokemon again, opening the menu where it asks if you want to select this pokemon or not. After that, it waits a bit, closes that menu, and THEN leaves the trade
Sometimes it even enters this menu multiple times before leaving.

When i watch bots on twitch it seems that some other people have this problem, and some don't, so i'm not sure if it's normal or not?

Is there any way to fix this? I'm on sysbotbase 1.6, and even tried redownloading a fresh sysbot program.

**Comment by Lusamine** [comment]
It can be normal to wait before exiting a trade. 

Opening Y comm multiple times is not normal.  Read the error logs to see what is happening. Usually it's a botbase/wifi connection issue or a screen detection problem.  Try changing the screen detection setting to the other detection mode.  

Not a sysbot code problem though, something specific to your setup since it's not happening for other users.
