### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ikelz14** [kwsch/SysBot.NET#106]
The distribution while idle idea is a wonderfull one! But would it be possible for the bot to surprise trade from the distribution folder like the dedicated suprisetrade bot while being say a link trading bot? 

In simple terms I would want my link trade bot to suprise trade when its not being used

**Comment by kwsch** [comment]
We generally don't want people doing automated surprise trading, as it's the most-spammy way of sending out trash.

Flex Trade already has Distribute-While-Idle, which distributes to a fixed trade code. People opt-in to receiving your junk from that trade code, rather than surprise trade being a complete free-for-all.

Users have had great success with distribute-while-idle and the ledy-trade functions during the bot's idle time. I don't think surprise trading is necessary at all. We don't want people abusing surprise trade to advertise their bots during their bots idle time. They'd have to be exclusively surprise trade if they really want to surprise trade.
