### ISSUE TITLE
"Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index" is to confusing, make an exception handler.

### ISSUE THREAD

**Issue by Exyrus** [kwsch/SysBot.NET#145]
title
if thats not possible, sorry, ignore this issue

**Comment by Lusamine** [comment]
Scroll higher in the error log and read all the errors.

**Comment by Exyrus** [comment]
i know what the error means but i was thinking to make an exception handler

**Comment by kwsch** [comment]
You did not indicate where this error was being shown. Assuming this was for a user entered discord command.

The program already handles exceptions sufficiently; adding in try-catch/handling for every place users can screw up text data is kinda overkill when the program already indirectly says "oops, couldn't handle that command", and spits out the error message instead of silently failing.

**Comment by Exyrus** [comment]
ah, i should've been more specific

this error is in a discord command.
if you make a typo (or just type something that doesnt exist in any game) at the pokemon name part, it spits out the very long message that is in the issue name. people who are less experienced might not know what that means.

instead, i was saying that it should say something like "Error: "(what the user typed)" is not a valid Pokemon."

**Comment by Lusamine** [comment]
If the issue is the person is not requesting an appropriate Pokemon, it should be incredibly obvious to anyone looking that they don't know what Pokemon are.
