### ISSUE TITLE
Hyper Training/Trained: What Command Enables/Disables it.

### ISSUE THREAD

**Issue by CresentChaos** [kwsch/SysBot.NET#152]
Hello,

So I'm running into an issue where SysBot is creating a Hyper Trained Pokemon, my question is, is there a command that tells sysbot when to hyper train and which stat to hyper train a Pokemon in?
I can't seem to find any info on said command.

**Comment by Lusamine** [comment]
There isn't a command because this is part of autolegality-mod's batch editor functionally. You can look up the autolegality mod wiki and learn to use the batch editor on PKHeX to disable Hyper Training.

As I told you several times already on Discord, bot user questions should go to the host of the bot you are using. Otherwise, you can figure out the answer by reading the guides yourself.

https://github.com/architdate/PKHeX-Plugins/wiki/ALM-Showdown-Sets
https://projectpokemon.org/home/forums/topic/45398-using-pkhex-how-to-use-the-batch-editor-in-pkhex/

This is not a sysbot issue.
