### ISSUE TITLE
"Suspicious Activity" reason is highly ambiguous and doesn't help end users

### ISSUE THREAD

**Issue by teward** [kwsch/SysBot.NET#176]
In current Sysbot implementation (at least that's on PKCL and others), "Suspicious Activity" is a highly ambiguous message, and does not help end users understand *why* they're hitting suspicious activity.

While this in my case of encountering this is because I play both Violet and Scarlet, and encountered a 'conflicting account' issue here, this is highly infinitely ambiguous from "SuspiciousActivity" and requires users to hunt down the bot masters to actually figure out what this means from the monitoring folder.

**This is bad UX.**  It'd be more effective to give a notice like "SuspiciousActivity: Reason" so those of us who run into issues like I stated (not abuse but two different games is all) to the end user rather than simply giving the ambiguous reason.

**Comment by Lusamine** [comment]
It is intentionally ambiguous because that error is meant to catch people selling out of sysbots. It is the job of the bot owner to investigate each one to decide if they think it is true abuse or not.  Giving a more specific reason to bypass bot owners helps abusers avoid detection.

Working as intended.
