### ISSUE TITLE
Pokemon nickname of numbers causes issues

### ISSUE THREAD

**Issue by htcord** [kwsch/SysBot.NET#179]
If someone requests a pokemon with just numbers for the nickname, the pokemon generated will not have the nickname and the trade code will end up being the number the nickname was supposed to be instead, despite the bot being set up to have a specified range of numbers not including the number of the nickname.

**Comment by kwsch** [comment]
Nicknames can't be 5+ just numbers. Do you have an example request string?

**Comment by kwsch** [comment]
This is probably due to command recognition seeing a valid int32 as a trade code request, then the remainder being the set.

Probably should just tell the user to NOT request a number only nickname, and to nickname it themselves in game.

**Comment by kwsch** [comment]
Closing due to the way commands are handled; I don't see any real value added in adding abort code for the {int} {remainder set} command to have it instead call the fallback $"{int} {remainder}" handler.

If they really must have a nickname, they can nickname in-game. Or, they can reverse the Species and Nickname order as the PKHeX.Core parser can handle that too.

**Comment by htcord** [comment]
Sorry for the delayed response, was traveling over the weekend. Agree, can tell users to just not request numbers. 
Example was someone requesting a four digit number, 1989, as the username and then the trade code became 0000-1989. For what's it's worth, paste was:

1989 (Rotom-Wash) @ Leftovers  
Ability: Levitate  
Tera Type: Electric  
EVs: 252 HP / 4 SpA / 252 SpD  
Calm Nature  
IVs: 0 Atk  
- Hydro Pump  
- Thunderbolt  
- Protect  
- Will-O-Wisp
