### ISSUE TITLE
Building on Rider

### ISSUE THREAD

**Issue by Owy** [kwsch/SysBot.NET#64]
Hello!

I've been trying to run the bot from source, in case I find something useful to contribute.  
As a Java/Linux dev, my first attempt was to open it using Rider on my Windows to be almost-at-home ; but building the project throws some errors:

![image](https://user-images.githubusercontent.com/6304157/79602154-44037000-80ea-11ea-9836-b190ffaa1dd8.png)

I was able to "fix" the first two by adding a Nuget dependency on `System.Resources.Extensions` and adding the variable that Rider complains about in `SysBot.Pokemon.WinForms.csproj`. The 3rd one I have no idea 😕 

Build works & runs on Visual Studio, so I'm not entierly sure if it's a problem with Rider, my configuration ; or if I should open a PR with my changes because VS shouldn't be able to build without them.

I have .Net Framework DevPack 4.7 & .Net Core 3.1.201 installed. MSBuild is from .Net Core 3.1.

Any pointers would be appreciated!

**Comment by kwsch** [comment]
Probably due to VS using the old build methods, while Rider uses `dotnet build`:

`https://github.com/microsoft/msbuild/issues/4704#issuecomment-530034240`

![image](https://user-images.githubusercontent.com/6393368/79608938-ae94bb80-80aa-11ea-8c72-2eb0c4ef80dc.png)

The Fody stuff is just to merge in the dlls to the main exe.

I think what we can do to alleviate the .NET Core builds is:

```
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4')) AND '$(Configuration)' == 'Release'">
    <PackageReference Include="Costura.Fody" Version="4.1.0" />
    <PackageReference Include="Fody" Version="6.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

This should only reference Fody for dll wrapping on the release builds.

For the `System.Resources.Extensions`:

```
  <ItemGroup Condition="'$(TargetFramework.StartsWith('netcore'))'">
    <PackageReference Include="System.Resources.Extensions" Version="4.7.0" />
  </ItemGroup>

  <PropertyGroup Condition="$(TargetFramework.StartsWith('netcore'))">
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
```

Something like ^... I'm not too knowledgeable with this stuff :D

So yeah, if you get things working with Rider, a PR would be nice!
